#!/bin/sh
case "$1" in
  start)
        echo "Configuring wifi"
        
        if [ ! -f "/mnt/wpa_supplicant/wpa_supplicant.conf" ]; then
        	mkdir -p /mnt/wpa_supplicant
		cp /etc/wpa_supplicant/wpa_supplicant.conf /mnt/wpa_supplicant/wpa_supplicant.conf
	fi
	
	rm /etc/wpa_supplicant/wpa_supplicant.conf
	ln -s /mnt/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf
        
	python3 /etc/wifi/start_wifi.py
        ;;
  stop)
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
